### ISSUE TITLE
Print intermediate steps - higher transparency for calculations

### ISSUE THREAD

**Issue by r7butler** [SCCWRP/SQOUnified#2]
Hiram from San Diego Water Board suggested printing intermediate steps so that there is better transparency in the calculations especially for the benthic indices.

Maybe adding a verbose option to the functions would be the way to do it

**Comment by nickharing** [comment]
What might be equally useful is some way to show which data are being used for a given analysis and which are not. For example, BRI is calculated using only the taxa that match the P-code list. Sometimes taxa that should be included in the BRI calcs are misspelled and thus excluded. We can add spell checking, but initially, end-users might appreciate being able to manually review the subsetted taxa list.
